export const LOGIN_TWITTER = 'LOGIN_TWITTER';
export const LOGOUT_TWITTER = 'LOGOUT_TWITTER';
export const TWITT_TWITTER = 'TWITT_TWITTER';
export const SET_TWITT_TWITTER = 'SET_TWITT_TWITTER';
export const SET_LOGIN_TWITTER = 'SET_LOGIN_TWITTER';
export const SET_INPUT_TWITTER = 'SET_INPUT_TWITTER';
export const LIKE_TWITTER = 'LIKE_TWITTER';
export const COMMENT_TWITTER = 'COMMENT_TWITTER';
